- platform: webhooks
  api_key: !secret telegram_bot_api_key
  parse_mode: markdown
  allowed_chat_ids:
    - !secret telegram_groupchat_id
    - !secret telegram_georgechat_id
    - !secret telegram_vivianchat_id