homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Athens
  external_url: !secret ha_external_url
  internal_url: !secret ha_internal_url
  customize: !include customize.yaml

default_config:
mobile_app:
lovelace:
  mode: yaml

ios:                 !include integrations/ios_push.yaml
tts:                 !include integrations/google_text_to_speach.yaml
http:                !include integrations/http.yaml
alert:               !include integrations/alerts.yaml
group:               !include groups.yaml
camera:              !include integrations/camera.yaml
script:              !include scripts.yaml
homekit:             !include assistants/siri.yaml
climate:             !include integrations/climate.yaml
yeelight:            !include integrations/yeelight.yaml
input_text:          !include integrations/input_texts.yaml
telegram_bot:        !include integrations/telegram_bot.yaml
input_boolean:       !include integrations/input_booleans.yaml
google_assistant:    !include assistants/google.yaml
circadian_lighting:  !include integrations/circadian.yaml
alarm_control_panel: !include integrations/alarm_cpanel.yaml
vacuum:              !include integrations/vacuum.yaml
light:               !include_dir_merge_list lights/
notify:              !include_dir_merge_list notifiers/
switch:              !include_dir_merge_list switches/
sensor:              !include_dir_merge_list sensors/
automation:          !include_dir_merge_list automations/