- alias: 'Ventilation - Override house'
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/houseforceventilate'
  mode: single
  action:
    - service: input_boolean.turn_on
      data:
        entity_id:
          - input_boolean.living_room_ventilated
          - input_boolean.bedroom_ventilated
          - input_boolean.kitchen_ventilated
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: '🌪️ All rooms marked as ventilated'
    - service: telegram_bot.edit_message
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.user_id }}'
        title: '🌪️ *[Daily choirs]*'
        message: |
          
          Room ventilation status:

          {% if is_state('input_boolean.kitchen_ventilated', 'on') -%}
            ✔️ *Kitchen*
          {% else %}
            ❌ *Kitchen*
          {% endif %}
          {%- if is_state('input_boolean.living_room_ventilated', 'on') -%}
            ✔️ *Living room*
          {% else %}
            ❌ *Living room*
          {% endif %}
          {%- if is_state('input_boolean.bedroom_ventilated', 'on') -%}
            ✔️ *Bedroom*
          {% else %}
            ❌ *Bedroom*
          {% endif %}
          Try opening their respective windows for at least *15mins*.

        parse_mode: markdown
        inline_keyboard: []

- alias: 'Ventilation - Override kitchen'
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/kitchenforceventilate'
  mode: single
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.kitchen_ventilated
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: '🌪️ Kitchen marked as ventilated'
    - service: telegram_bot.edit_message
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.user_id }}'
        title: '🌪️ *[Daily choirs]*'
        message: |
          
          Room ventilation status:

          {% if is_state('input_boolean.kitchen_ventilated', 'on') -%}
            ✔️ *Kitchen*
          {% else %}
            ❌ *Kitchen*
          {% endif %}
          {%- if is_state('input_boolean.living_room_ventilated', 'on') -%}
            ✔️ *Living room*
          {% else %}
            ❌ *Living room*
          {% endif %}
          {%- if is_state('input_boolean.bedroom_ventilated', 'on') -%}
            ✔️ *Bedroom*
          {% else %}
            ❌ *Bedroom*
          {% endif %}
          Try opening their respective windows for at least *15mins*.

        parse_mode: markdown
        inline_keyboard: >
          {% set ns = namespace(items=[ 'Force ventilate all rooms:/houseforceventilate' ]) %}
          {% if is_state('input_boolean.kitchen_ventilated', 'off') %}
            {% set ns.items = ns.items + [ 'Force ventilate kitchen:/kitchenforceventilate' ] %}
          {% endif %}
          {% if is_state('input_boolean.living_room_ventilated', 'off') %}
            {% set ns.items = ns.items + [ 'Force ventilate living room:/livingroomforceventilate' ] %}
          {% endif %}
          {% if is_state('input_boolean.bedroom_ventilated', 'off') %}
            {% set ns.items = ns.items + [ 'Force ventilate bedroom:/bedroomforceventilate' ] %}
          {% endif %}
          {{ ns.items }}

- alias: 'Ventilation - Override living room'
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/livingroomforceventilate'
  mode: single
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.living_room_ventilated
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: '🌪️ Living room marked as ventilated'
    - service: telegram_bot.edit_message
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.user_id }}'
        title: '🌪️ *[Daily choirs]*'
        message: |
          
          Room ventilation status:

          {% if is_state('input_boolean.kitchen_ventilated', 'on') -%}
            ✔️ *Kitchen*
          {% else %}
            ❌ *Kitchen*
          {% endif %}
          {%- if is_state('input_boolean.living_room_ventilated', 'on') -%}
            ✔️ *Living room*
          {% else %}
            ❌ *Living room*
          {% endif %}
          {%- if is_state('input_boolean.bedroom_ventilated', 'on') -%}
            ✔️ *Bedroom*
          {% else %}
            ❌ *Bedroom*
          {% endif %}
          Try opening their respective windows for at least *15mins*.

        parse_mode: markdown
        inline_keyboard: >
          {% set ns = namespace(items=[ 'Force ventilate all rooms:/houseforceventilate' ]) %}
          {% if is_state('input_boolean.kitchen_ventilated', 'off') %}
            {% set ns.items = ns.items + [ 'Force ventilate kitchen:/kitchenforceventilate' ] %}
          {% endif %}
          {% if is_state('input_boolean.living_room_ventilated', 'off') %}
            {% set ns.items = ns.items + [ 'Force ventilate living room:/livingroomforceventilate' ] %}
          {% endif %}
          {% if is_state('input_boolean.bedroom_ventilated', 'off') %}
            {% set ns.items = ns.items + [ 'Force ventilate bedroom:/bedroomforceventilate' ] %}
          {% endif %}
          {{ ns.items }}

- alias: 'Ventilation - Override bedroom'
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/bedroomforceventilate'
  mode: single
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bedroom_ventilated
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: '🌪️ Bedroom marked as ventilated'
    - service: telegram_bot.edit_message
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.user_id }}'
        title: '🌪️ *[Daily choirs]*'
        message: |
          
          Room ventilation status:

          {% if is_state('input_boolean.kitchen_ventilated', 'on') -%}
            ✔️ *Kitchen*
          {% else %}
            ❌ *Kitchen*
          {% endif %}
          {%- if is_state('input_boolean.living_room_ventilated', 'on') -%}
            ✔️ *Living room*
          {% else %}
            ❌ *Living room*
          {% endif %}
          {%- if is_state('input_boolean.bedroom_ventilated', 'on') -%}
            ✔️ *Bedroom*
          {% else %}
            ❌ *Bedroom*
          {% endif %}
          Try opening their respective windows for at least *15mins*.

        parse_mode: markdown
        inline_keyboard: >
          {% set ns = namespace(items=[ 'Force ventilate all rooms:/houseforceventilate' ]) %}
          {% if is_state('input_boolean.kitchen_ventilated', 'off') %}
            {% set ns.items = ns.items + [ 'Force ventilate kitchen:/kitchenforceventilate' ] %}
          {% endif %}
          {% if is_state('input_boolean.living_room_ventilated', 'off') %}
            {% set ns.items = ns.items + [ 'Force ventilate living room:/livingroomforceventilate' ] %}
          {% endif %}
          {% if is_state('input_boolean.bedroom_ventilated', 'off') %}
            {% set ns.items = ns.items + [ 'Force ventilate bedroom:/bedroomforceventilate' ] %}
          {% endif %}
          {{ ns.items }}